# Workflow to build and publish to gh-pages

name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check-out source
        uses: actions/checkout@v2
      - name: setup environemnt
        run: |
          apt update
          apt-get install -y ruby-full build-essential zlib1g-dev
          gem install jekyll bundler
      - name: install dependencies
        run: bundle install
      - name: build
        run: bundle exec jekyll build
      - name: upload artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: site
          path: ${{ github.workspace }}/_site
  publish:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Check-out source
        uses: actions/checkout@v2
      - name: download site
        uses: actions/download-artifact@v2.0.10
        with:
          name: site
          path: ${{ github.workspace }}/publish
